SELECT COUNT(ITEMNAME)AS TOPLAM_ITEM FROM SALES--TOPLAM KAYIT
SELECT COUNT(DISTINCT ITEMNAME)AS FARKLI_ITEM FROM SALES --FARKLI KAYIT LÝSTESÝ
--SELECT COUNT(DISTINCT PRICE) FROM SALES WHERE PRICE>5
SELECT COUNT(*)FROM SALES WHERE PRICE>5--5 FÝYATINDAN BÜYÜK KAÇ ÜRÜN VAR
SELECT COUNT(AMOUNT) AS ELDEKI_MAL FROM SALES WHERE AMOUNT>0