SELECT 

R.KNO,R.KISI,R.MADI1,R.ACENTAKODU,RD.COCUK,RD.COCUK2,RD.BEBEK,RD.ACENTAID,R.ODANO,R.ODAFIYATI,R.CITARIHI,R.COUTTARIHI,
SUM(R.ODAFIYATI) AS TOPLAMFIYAT
FROM RES AS R  JOIN RESDAYS AS RD ON R.KNO=RD.KNO AND R.ACENTAID=RD.ACENTAID
GROUP BY R.KNO,R.MADI1,R.ACENTAKODU,RD.COCUK,RD.COCUK2,RD.BEBEK,RD.ACENTAID,R.ODANO,R.ODAFIYATI,R.CITARIHI,R.COUTTARIHI,R.KISI

ORDER BY KNO
   




--////////////////////////////////////////////
  -- WHERE R.KNO=4
--select * from RES
--SELECT * FROM RESDAYS R
--RIGHT JOIN RES RD ON RD.KNO=R.KNO