---------------------------------------COLUMN DÝLÝ DEÐÝÞTÝRME

--SELECT name, collation_name FROM sys.databases

--CREATE TABLE [dbo].[OGRENCI](

  --  [AdSoyad] [char](10) COLLATE Turkish_CI_AS NULL

--) ON [PRIMARY]

--ALTER TABLE [dbo].[OGRENCI]
--COLLATE  SQL_Latin1_General_CP1254_CI_AS;
--GO

USE ELEKTRA
GO
Select TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, COLLATION_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'dbo'
AND TABLE_NAME = 'ACENTA'
AND COLUMN_NAME = 'ACIKLAMA'


USE ELEKTRA
GO
ALTER TABLE [dbo].[ACENTA]
ALTER COLUMN ACIKLAMA NVARCHAR(4000)
COLLATE Uzbek_Latin_100_CS_AI_KS_WS NULL
GO


--EXEC  SP_RENAME 'OGRENCI','col_test';

