SELECT 
rd.TARIH,
R.KNO,R.MADI1 AS MISAFIR,R.CITARIHI AS CHECINTARIHI,R.COUTTARIHI AS CHECKOUTTARIHI,R.ACENTAKODU,RD.KISI,RD.COCUK,RD.COCUK2,RD.BEBEK,RD.ACENTAID,R.ODANO,RD.ODAFIYATI AS ODAFIYAT_DOVIZ,RD.DOVIZKODU,RD.DOVIZKURU,RD.ODAFIYATI*RD.DOVIZKURU AS ODAFIYATI_TL
--SUM(R.ODAFIYATI) AS MAAS
FROM RES AS R  JOIN RESDAYS AS RD ON R.KNO=RD.KNO AND R.ACENTAID=RD.ACENTAID

ORDER BY KNO
   


   --SELECT * FROM RESDAYS WHERE KNO=6