Create View getmýsafýr_2
As
SELECT MISAFIR.MID,MISAFIR.AD,MISAFIR.SOYAD,MISAFIR.UNVANI,MISAFIR.CINSIYETI,MISAFIR.UYRUK,MISAFIR.ULKE,MISAFIR.EMAIL,RES.ACENTAKODU
FROM RES
JOIN REZKISI ON RES.KNO=REZKISI.KNO
JOIN MISAFIR ON REZKISI.MID=MISAFIR.MID

