--SELECT MADI1 FROM RES
SELECT MISAFIR.MID,MISAFIR.AD,MISAFIR.SOYAD,MISAFIR.UNVANI,MISAFIR.CINSIYETI,MISAFIR.UYRUK,MISAFIR.ULKE,MISAFIR.EMAIL,RES.ACENTAKODU
FROM RES
Left JOIN REZKISI ON RES.KNO=REZKISI.KNO
left JOIN MISAFIR ON REZKISI.MID=MISAFIR.MID


where res.KNO=5


--SELECT AD,SOYAD FROM MISAFIR
--SELECT * FROM getmýsafýr_2