USE [anket]
GO

/****** Object:  Table [dbo].[ANKET]    Script Date: 13.03.2020 08:33:54 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ANKET](
	[anketid] [int] NOT NULL,
 CONSTRAINT [PK_anket] PRIMARY KEY CLUSTERED 
(
	[anketid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ANKET]  WITH CHECK ADD  CONSTRAINT [FK_anket_CEVAP] FOREIGN KEY([anketid])
REFERENCES [dbo].[CEVAP] ([cevapid])
GO

ALTER TABLE [dbo].[ANKET] CHECK CONSTRAINT [FK_anket_CEVAP]
GO

ALTER TABLE [dbo].[ANKET]  WITH CHECK ADD  CONSTRAINT [FK_anket_SORU] FOREIGN KEY([anketid])
REFERENCES [dbo].[SORU] ([ID])
GO

ALTER TABLE [dbo].[ANKET] CHECK CONSTRAINT [FK_anket_SORU]
GO


