USE [anket]
GO

/****** Object:  Table [dbo].[CEVAP]    Script Date: 13.03.2020 08:34:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CEVAP](
	[cevapid] [int] NOT NULL,
	[soruid] [int] NULL,
	[cevap] [nvarchar](150) NULL,
 CONSTRAINT [PK_cevap] PRIMARY KEY CLUSTERED 
(
	[cevapid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CEVAP]  WITH CHECK ADD  CONSTRAINT [FK_CEVAP_SORU] FOREIGN KEY([soruid])
REFERENCES [dbo].[SORU] ([ID])
GO

ALTER TABLE [dbo].[CEVAP] CHECK CONSTRAINT [FK_CEVAP_SORU]
GO


