USE [anket]
GO

/****** Object:  Table [dbo].[SORU]    Script Date: 13.03.2020 08:34:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SORU](
	[ID] [int] NOT NULL,
	[anketID] [int] NULL,
	[kategori] [nvarchar](100) NOT NULL,
	[soru] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_soru] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


