GO
-- Set to single-user mode
ALTER DATABASE [ELEKTRA]
SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
  
 
ALTER DATABASE [ELEKTRA]
COLLATE SQL_Latin1_General_CP1254_CS_AS;
GO  
 
-- Set to multi-user mode
ALTER DATABASE [ELEKTRA]
SET MULTI_USER WITH ROLLBACK IMMEDIATE;
GO 

--use ELEKTRA
  --  select    TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME  
    --from       INFORMATION_SCHEMA.COLUMNS    
    --where    COLUMN_NAME like '%REZTAKVIM%'
      --AND TABLE_CATALOG='ELEKTRA'
--GO

--SELECT COLUMN_NAME as FNFO4_ANKET, TABLE_NAME as Tablo_Adi 
--FROM INFORMATION_SCHEMA.COLUMNS 
--WHERE COLUMN_NAME LIKE 'FNFO4_ANKET'

SELECT
TABLE_CATALOG AS DATABASE_ADI
,TABLE_SCHEMA AS SCHEMA_ADI
,TABLE_NAME AS TABLO_ADI
,TABLE_TYPE AS TABLO_TÝPÝ
FROM INFORMATION_SCHEMA.TABLES
ORDER BY TABLO_TÝPÝ



USE AdvantureWorks
GO
Select TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, COLLATION_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'dbo'
AND TABLE_NAME = 'col_test'
AND COLUMN_NAME = 'Text'


